### ISSUE TITLE
HTPP Error on request from 2022 on

### ISSUE THREAD

**Issue by JotaFan** [SanPen/ESIOS#10]
HTTP Error 403: Forbidden

That is the error if we try the API on any 2022 afterwards date

**Comment by followingell** [comment]
@JotaFan Does the [`README.md`](https://github.com/SanPen/ESIOS/blob/master/README.md#warning) warning need to be removed given your PR? 🙂

> WARNING
> 
> The API is having troubles with request made from 2022 on, There is a limiter in place to not go to those dates.
