### ISSUE TITLE
Bug while loading data

### ISSUE THREAD

**Issue by alejandrogomez97** [SanPen/ESIOS#2]
Estoy usando tu modulo de esios para extraer datos de la api de esios. Hace un tiempo me iba todo perfectamente, pero ahora, en la función     df_list, names = esios.get_multiple_series(indicators_, start_, end_), me salta este error: 

![image](https://user-images.githubusercontent.com/116890811/212668225-b4bde20c-76bc-4f6e-b64d-46b6eb4a22e0.png)

Sabes qué puede estar pasando?

**Comment by SanPen** [comment]
Hola, 

Suena bastante raro.  [SO](https://stackoverflow.com/questions/75069062/module-numpy-has-no-attribute-object) puede tener la solución.

Tienes un archivo por ahí que se llama numpy?

**Comment by alejandrogomez97** [comment]
Trabajo en databricks, he instalado numpy previamente.

**Comment by alejandrogomez97** [comment]
Pero a ti te va ahora mismo? Es que yo calco el código y no me corre por eso

**Comment by alejandrogomez97** [comment]
Acabo de probar a cambiar la versión de numpy. He puesto la 1.22 y ya funciona. Parece ser que no va con la más reciente...
