### ISSUE TITLE
x-api-key does not work

### ISSUE THREAD

**Issue by huertamir** [SanPen/ESIOS#4]
I have a program which starts like this below and calls your program ESIOS updated. 

#%% CARGA PAQUETES
import pandas as pd
import numpy as np
import pickle
import urllib.request

from pandas.io import excel
from ESIOS import *
from datetime import datetime, timedelta
import pytz

# Inicia esios
x-api-key: 367ef4364c20bd6accfaf182f382d09885439eeb8b520a651faa0406e54c5178

esios = ESIOS(token)

When running appears:

x-api-key: 367ef4364c20bd6accfaf182f382d09885439eeb8b520a651faa0406e54c5178
  File "<ipython-input-23-32d1b378100c>", line 1
    x-api-key: 367ef4364c20bd6accfaf182f382d09885439eeb8b520a651faa0406e54c5178
                  ^
SyntaxError: invalid syntax

Could you help me please?

Many thanks in advance,
Almudena

**Comment by gabriel23cg** [comment]
Value of variable `token` must be just `'367...'`, not `'x-api-key...'`

**Comment by huertamir** [comment]
Solved, thanks a lot!
